name: Build and Release

on:
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Build plugin
        run: npm run build

      - name: Get plugin ID from manifest.json
        id: get_plugin_id
        run: echo "::set-output name=plugin_id::$(jq -r .id manifest.json)"
        shell: bash

      - name: Get version from manifest.json
        id: get_version
        run: echo "::set-output name=version::$(jq -r .version manifest.json)"
        shell: bash

      - name: Create release zip
        run: |
          zip ${{ steps.get_plugin_id.outputs.plugin_id }}.zip main.js manifest.json
        shell: bash

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          name: ${{ steps.get_version.outputs.version }}
          tag_name: ${{ steps.get_version.outputs.version }}
          files: ./${{ steps.get_plugin_id.outputs.plugin_id }}.zip

permissions:
  contents: write
